services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: sas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    image: guabiraba/sas
    depends_on:
      mysql:
        condition: service_healthy
    container_name: user-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8080"
volumes:
  mysql_data: